/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package com.xwiki.confluencepro.test.ui;

import java.io.File;
import java.util.List;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.xwiki.test.docker.junit5.ExtensionOverride;
import org.xwiki.test.docker.junit5.TestConfiguration;
import org.xwiki.test.docker.junit5.UITest;
import org.xwiki.test.ui.TestUtils;

import com.xwiki.confluencepro.test.po.ConfluenceHomePage;
import com.xwiki.confluencepro.test.po.CreateBatchPage;
import com.xwiki.confluencepro.test.po.MigrationCreationPage;
import com.xwiki.confluencepro.test.po.MigrationRaportView;
import com.xwiki.confluencepro.test.po.MigrationRunningPage;
import com.xwiki.confluencepro.test.po.QuestionSpace;

import static junit.framework.TestCase.assertEquals;
import static junit.framework.TestCase.assertFalse;
import static junit.framework.TestCase.assertTrue;

@UITest(properties = {
    // Add the FileUploadPlugin which is needed by the test to upload attachment files
    "xwikiCfgPlugins=com.xpn.xwiki.plugin.fileupload.FileUploadPlugin" },
    extensionOverrides = {
        @ExtensionOverride(
            extensionId = "com.google.code.findbugs:jsr305",
            overrides = {
                "features=com.google.code.findbugs:annotations"
            }
        )
    }
)
public class ConfluenceMigratorIT
{
    private static final String MIGRATION_TITLE = "NewMigration";

    private static final String USER_NAME = "JohnDoe";

    private static final String SINGLE_SPACE_PACKAGE = "confluence-package.zip";

    private static final String MULTI_SPACE_PACKAGE = "4.3.2.xml.zip";

    @BeforeAll
    void beforeAll(TestUtils testUtils)
    {
        testUtils.loginAsSuperAdmin();
        // The application creator needs script rights in order to execute the scripts generated by the wizard.
        testUtils.setGlobalRights("", "XWiki." + USER_NAME, "admin", true);
        testUtils.createUserAndLogin(USER_NAME, "pa$$word");
    }

    @Test
    @Order(1)
    void packageUpload(TestConfiguration testConfiguration)
    {
        ConfluenceHomePage.goToPage();
        ConfluenceHomePage confluenceHomePage = new ConfluenceHomePage();
        confluenceHomePage.openSection("confluence-pro-tab-container-new-migration");
        confluenceHomePage.openHowToMigrateSubsection(".uploadSubsection");
        confluenceHomePage.attachFiles(testConfiguration.getBrowser().getTestResourcesPath(),
            List.of(SINGLE_SPACE_PACKAGE, MULTI_SPACE_PACKAGE));
        assertTrue(confluenceHomePage.getPackageLiveTable().getTableLayout().countRows() > 0);
    }

    @Test
    @Order(2)
    void selectPackage()
    {
        ConfluenceHomePage.goToPage();
        ConfluenceHomePage confluenceHomePage = new ConfluenceHomePage();
        confluenceHomePage.openSection("confluence-pro-tab-container-new-migration");
        confluenceHomePage.openHowToMigrateSubsection(".uploadSubsection");

        MigrationCreationPage migrationCreationPage = confluenceHomePage.selectPackage(1);
        migrationCreationPage.clickAdvancedMigrationOptions();
        assertTrue(migrationCreationPage.getAdvancedInputFilterProperties().size() > 1);
        assertTrue(migrationCreationPage.getAdvancedOutputProperties().size() > 1);
    }

    @Test
    @Order(3)
    void runMigrationWithMultipleSpaces(TestConfiguration testConfiguration)
    {

        ConfluenceHomePage.goToPage();
        ConfluenceHomePage confluenceHomePage = new ConfluenceHomePage();
        confluenceHomePage.openSection("confluence-pro-tab-container-new-migration");
        confluenceHomePage.openHowToMigrateSubsection(".uploadSubsection");

        MigrationCreationPage migrationCreationPage = confluenceHomePage.selectPackage(1);
        migrationCreationPage.setTitle(MIGRATION_TITLE);
        migrationCreationPage.clickSaveAndView();
        MigrationRunningPage runningPage = new MigrationRunningPage();
        assertEquals(MIGRATION_TITLE, runningPage.getDocumentTitle());
        ConfluenceHomePage.goToPage();
        confluenceHomePage.openSection("confluence-pro-tab-container-all-migrations");
        // The latest migration will always be the one with index 0 because the livedata is sorted by date.
        String migrationStatus = confluenceHomePage.migrationStatus(0);
        assertEquals("Running", migrationStatus);
        //Go back and run the migration
        runningPage = confluenceHomePage.getMigrationRunningPage(0);
        QuestionSpace questionSpace = runningPage.getSelectableSpace(0);
        questionSpace.getCheckbox().click();
        MigrationRaportView raportView = runningPage.confirmSpacesToMigrate();

        assertEquals(1, raportView.getImportedSpaces().size());
        assertFalse(raportView.hasErrorLogs());
    }

    @Test
    @Order(4)
    void runMigrationWithSingleSpaces(TestConfiguration testConfiguration)
    {
        ConfluenceHomePage.goToPage();
        ConfluenceHomePage confluenceHomePage = new ConfluenceHomePage();
        confluenceHomePage.openSection("confluence-pro-tab-container-new-migration");
        confluenceHomePage.openHowToMigrateSubsection(".uploadSubsection");
        MigrationCreationPage migrationCreationPage = confluenceHomePage.selectPackage(2);
        migrationCreationPage.setTitle(MIGRATION_TITLE + "2");
        migrationCreationPage.clickSaveAndView();
        MigrationRaportView raportView = new MigrationRaportView();
        assertEquals(1, raportView.getImportedSpaces().size());
        assertFalse(raportView.hasErrorLogs());
    }

    @Test
    @Order(5)
    void runMigrationWithCustomOptions(TestConfiguration testConfiguration)
    {
        ConfluenceHomePage.goToPage();
        ConfluenceHomePage confluenceHomePage = new ConfluenceHomePage();
        confluenceHomePage.openSection("confluence-pro-tab-container-new-migration");
        confluenceHomePage.openHowToMigrateSubsection(".uploadSubsection");
        MigrationCreationPage migrationCreationPage = confluenceHomePage.selectPackage(2);
        migrationCreationPage.setTitle(MIGRATION_TITLE + "3");
        migrationCreationPage.clickAdvancedMigrationOptions();
        migrationCreationPage.fillOption("archivedDocumentsEnabled", "true");
        migrationCreationPage.clickSaveAndView();
        MigrationRaportView raportView = new MigrationRaportView();
        assertEquals(1, raportView.getImportedSpaces().size());
        assertFalse(raportView.hasErrorLogs());
    }

    @Test
    @Order(6)
    void testMigrationOptionForms()
    {
        testMigrationOptions("confluence-pro-tab-container-new-migration", ".uploadSubsection",
            ".cmpUploadPackageMigrationSettingsForm", "default", "false");
        testMigrationOptions("confluence-pro-tab-container-new-migration", ".uploadSubsection",
            ".cmpUploadPackageMigrationSettingsForm", "specified", "true");
    }

    /**
     * Check that all sections are loaded.
     */
    @Test
    @Order(7)
    void changeSection()
    {
        ConfluenceHomePage.goToPage();
        ConfluenceHomePage confluenceHomePage = new ConfluenceHomePage();
        confluenceHomePage.openSection("confluence-pro-tab-container-new-migration");
        assertTrue(confluenceHomePage.checkIfSectionWasLoaded(".confluence-pro-tab-container-new-migration"));
        confluenceHomePage.openSection("confluence-pro-tab-container-all-migrations");
        assertTrue(confluenceHomePage.checkIfSectionWasLoaded(".confluence-pro-tab-container-all-migrations"));
        confluenceHomePage.openSection("confluence-pro-tab-container-imported-macros");
        assertTrue(confluenceHomePage.checkIfSectionWasLoaded(".confluence-pro-tab-container-imported-macros"));
        confluenceHomePage.openSection("confluence-pro-tab-container-post-migration-fixes");
        assertTrue(confluenceHomePage.checkIfSectionWasLoaded(".confluence-pro-tab-container-post-migration-fixes"));
    }

    /**
     * Check that the buttons work and the packages are selected.
     */
    @Test
    @Order(8)
    void batchPackageSelectorButtons(TestConfiguration testConfiguration)
    {
        ConfluenceHomePage.goToPage();
        ConfluenceHomePage confluenceHomePage = new ConfluenceHomePage();
        confluenceHomePage.openSection("confluence-pro-tab-container-new-migration");
        confluenceHomePage.openHowToMigrateSubsection(".batchSubsection");
        CreateBatchPage createBatchPage = confluenceHomePage.createNewBatch();
        createBatchPage.completePath(new File(testConfiguration.getBrowser().getTestResourcesPath()).getAbsolutePath())
            .refreshPage();
        createBatchPage.selectAll();
        assertEquals(2, createBatchPage.countSelectedPackages());
        createBatchPage.selectNone();
        assertEquals(0, createBatchPage.countSelectedPackages());
        createBatchPage.inverseSelection();
        assertEquals(2, createBatchPage.countSelectedPackages());
    }

    /**
     * Create a new batch.
     */
    @Test
    @Order(9)
    void createNewBatch(TestConfiguration testConfiguration)
    {
        ConfluenceHomePage.goToPage();
        ConfluenceHomePage confluenceHomePage = new ConfluenceHomePage();
        confluenceHomePage.openSection("confluence-pro-tab-container-new-migration");
        confluenceHomePage.openHowToMigrateSubsection(".batchSubsection");
        CreateBatchPage createBatchPage = confluenceHomePage.createNewBatch();
        createBatchPage.completePath(new File(testConfiguration.getBrowser().getTestResourcesPath()).getAbsolutePath())
            .refreshPage().completeName("Test");
        createBatchPage.selectAll();
        createBatchPage.createBatch();
        ConfluenceHomePage.goToPage();
        confluenceHomePage.openSection("confluence-pro-tab-container-new-migration");
        confluenceHomePage.openHowToMigrateSubsection(".batchSubsection");
        //Check that the batch was created.
        assertTrue(confluenceHomePage.countBatches() >= 1);
    }

    private void testMigrationOptions(String sectionId, String subsectionClass, String formSelector, String option,
        String expectedValue)
    {
        ConfluenceHomePage.goToPage();
        ConfluenceHomePage confluenceHomePage = new ConfluenceHomePage();
        confluenceHomePage.openSection(sectionId);
        confluenceHomePage.openHowToMigrateSubsection(subsectionClass);
        confluenceHomePage.selectMigrationOptions(formSelector, option);
        MigrationCreationPage migrationCreationPage = confluenceHomePage.selectPackage(2);
        migrationCreationPage.clickAdvancedMigrationOptions();
        assertEquals(expectedValue, migrationCreationPage.getOptionValue("archivedDocumentsEnabled"));
    }
}
